# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__, np.show_config()

Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/g6/rgtlsw6n123b0gt5483s5_cm0000gn/T/build-env-l0yq

('2.1.3', None)

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
z = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [9]:
z.itemsize*z.size

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
np.info(z)

class:  ndarray
shape:  (10,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x15a81b470
byteorder:  little
byteswap:  False
type: float64


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
z = np.arange(10, 50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [14]:
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
z = np.arange(9).reshape(3, 3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
np.nonzero(np.array([1, 2, 0, 0, 4, 0]))

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
z1 = np.ones(9).reshape(3, 3)
z2 = np.eye(3)
z1, z2

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
z = np.random.random((3, 3, 3))*100
z

array([[[56.12327486,  5.34604251, 17.02950757],
        [49.22729726, 28.01388015,  8.12974995],
        [ 5.87943972, 97.99452393, 55.12188661]],

       [[49.11924217, 41.30079512, 79.15397278],
        [ 5.37525883, 72.18776589, 62.97388069],
        [18.21378945, 50.51167697,  9.03660125]],

       [[99.35233932, 45.04925457, 69.43724202],
        [27.65073463, 26.88475639, 18.82480193],
        [64.67806083, 53.61977544,  8.94727937]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
z = np.random.random((10, 10))*1000
z.min(), z.max()

(np.float64(6.691809861240294), np.float64(999.6092501174634))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
z = np.random.random(30)
z.mean()

np.float64(0.43413632130929075)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
z = np.zeros(12).reshape(3, 4)
z[0] = 1
z[-1] = 1
z[:, 0] = 1
z[:, -1] = 1
z

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [ ]:
z = np.ones((10, 10)).astype("int")
z[1:-1, 1:-1] = 0
z

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
z = np.ones((5, 5)).astype("int")*1
z = np.pad(z, pad_width=3, mode="constant", constant_values=5)
z

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 1, 1, 1, 1, 1, 5, 5, 5],
       [5, 5, 5, 1, 1, 1, 1, 1, 5, 5, 5],
       [5, 5, 5, 1, 1, 1, 1, 1, 5, 5, 5],
       [5, 5, 5, 1, 1, 1, 1, 1, 5, 5, 5],
       [5, 5, 5, 1, 1, 1, 1, 1, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [56]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
np.diag(np.arange(1, 5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
z = np.zeros((8, 8), dtype="int")
z[::2, ::2] = 1
z[1::2, 1::2] = 1
print(z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
print(np.unravel_index([99], (6, 7, 8)))
print(np.unravel_index([99, 177, 33], (6, 7, 8)))

# unravel_index(indices, shape, order='C')

# Converts a flat index or array of flat indices into a tuple of coordinate arrays.

(array([1]), array([5]), array([3]))
(array([1, 3, 0]), array([5, 1, 4]), array([3, 1, 1]))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
basic = np.array([[1, 0], [0, 1]])
np.tile(basic, (4, 4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
z = np.random.randint(1, 20, (5, 5))
z = (z-np.mean(z))/np.std(z)
z, z.diagonal()

(array([[ 0.6952378 ,  0.5160528 , -1.27579719, -1.27579719,  0.3368678 ],
        [-0.7382422 , -1.27579719, -0.2006872 ,  0.6952378 ,  1.77034779],
        [-0.7382422 , -0.7382422 , -0.9174272 ,  1.77034779, -1.45498219],
        [ 0.8744228 , -0.9174272 ,  0.8744228 ,  0.8744228 ,  0.6952378 ],
        [-0.0215022 ,  0.6952378 , -1.27579719, -0.3798722 ,  1.41197779]]),
 array([ 0.6952378 , -1.27579719, -0.9174272 ,  0.8744228 ,  1.41197779]))

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [96]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
(np.ones((5, 3)) @ np.ones((3, 2))).astype("int")

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
z = np.arange(15)
np.where(((z > 3) & (z < 8)), -1*z, z)
# aliter: z[(z>3)&(z<8)] *= -1

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
"""
print(sum(range(5), -1))  # Output: 9
from numpy import *
print(sum(range(5), -1))  # Output: 10
"""

`sum` in line 1 is the regular sum function which takes an iterable and starting value as its two parameters.
`sum` in line 3 is the numpy.sum function which takes an array and its second argument is axis (which is irrelevant for 1D)

Thus, output is 9 and 10 resp.

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.array([[1, 9, 5, 1, 1]], dtype="int")
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z < - Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z) # ERRRROOOOORRRRR

[[1 9 5 1 1]]
[[        1 387420489      3125         1         1]]
[[  1 256  16   1   1]]
[[False False False False False]]
[[0.+1.j 0.+9.j 0.+5.j 0.+1.j 0.+1.j]]
[[1. 9. 5. 1. 1.]]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [145]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


/var/folders/n5/0y5w9mn17bvd48d064x7097w0000gn/T/ipykernel_30523/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/n5/0y5w9mn17bvd48d064x7097w0000gn/T/ipykernel_30523/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/n5/0y5w9mn17bvd48d064x7097w0000gn/T/ipykernel_30523/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
import numpy as np
Z = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
# print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

"""
Z is assigned an array of 10 random floating-point numbers. These numbers are generated using the 
np.random.uniform function, which creates random numbers uniformly distributed between the specified
`low` and `high` values, in this case, -10 and +10. This means that each number in the array Z will be a random value within this range.

The expression np.copysign(np.ceil(np.abs(Z)), Z) performs a series of transformations on Z.

1. np.abs(Z): computes the absolute value of each element in Z, effectively removing any negative signs.
2. np.ceil(np.abs(Z)): takes the ceiling of each absolute value, which means it rounds each number up to the nearest integer.
3. np.copysign(np.ceil(np.abs(Z)), Z):assigns the original sign of each element in Z to the corresponding ceiling value. 
This means that if an element in Z was negative, the resulting value will also be negative,
and if it was positive, the resulting value will be positive.

The final output is an array of integers where each integer is the ceiling of the absolute value of the corresponding element in
Z, but with the original sign of that element preserved. This combination of functions showcases the versatility and power of NumPy 
for performing complex numerical operations in a concise and readable manner."""

[  9.   2.   1.  10.   5.  -9.  -8. -10.   7.  -6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print(Z1, Z2, np.intersect1d(Z1, Z2, return_indices=True))

[0 5 3 4 3 9 6 1 3 9] [3 0 1 6 9 2 1 3 7 8] (array([0, 1, 3, 6, 9]), array([0, 7, 2, 6, 5]), array([1, 2, 0, 3, 4]))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# # Suicide mode on
# defaults = np.seterr(all="ignore")
# Z = np.ones(1) / 0

# # Back to sanity
# _ = np.seterr(**defaults)

# # Equivalently with a context manager
# with np.errstate(all="ignore"):
#     np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
print(np.emath.sqrt(-1))
print(np.sqrt(-1))

False
1j
nan


/var/folders/n5/0y5w9mn17bvd48d064x7097w0000gn/T/ipykernel_37954/1819156215.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))
/var/folders/n5/0y5w9mn17bvd48d064x7097w0000gn/T/ipykernel_37954/1819156215.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
yesterday, today, tomorrow

(np.datetime64('2024-12-04'),
 np.datetime64('2024-12-05'),
 np.datetime64('2024-12-06'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [15]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

# These operations demonstrate how NumPy's in-place operations can be used to efficiently
# manipulate arrays without creating additional copies,

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
Z = np.random.uniform(0, 10, 5)

print(Z)
print(Z - Z % 1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[8.70310815 2.31758302 4.08579935 2.83759883 4.26963477]
[8. 2. 4. 2. 4.]
[8. 2. 4. 2. 4.]
[8. 2. 4. 2. 4.]
[8 2 4 2 4]
[8. 2. 4. 2. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.zeros((5, 5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5, 1))
print(Z)

# another attempt
Z = np.random.randint(0, 5, (5, 5))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[1 1 3 2 3]
 [0 4 1 4 3]
 [0 1 3 2 4]
 [4 0 4 4 4]
 [2 2 2 0 3]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [2]:
import numpy as np

In [ ]:
def gen():
    for x in range(10):
        yield x


# count is default -1, meaning all elems from gen
z = np.fromiter(gen(), dtype="int", count=5)
z, z[3]

(array([0, 1, 2, 3, 4]), np.int64(3))

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
z1 = np.random.random(10)
z = np.linspace(0, 1, 11, endpoint=False)[1:]
"""
This generates 11 evenly spaced numbers between 0 (inclusive) and 1 (exclusive).
The endpoint=False parameter ensures that the stop value (1) is not included.
The np.linspace function is useful for creating sequences of numbers over a specified range.
[1:] removes the first element ie 0 thus making the size 10.
"""

print(z, z1, sep="\n")

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
[0.32947776 0.67123778 0.34092719 0.89886502 0.40722839 0.66397463
 0.52658517 0.49641352 0.30305396 0.74022592]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
z = np.random.random(10)
print(z)
z.sort()
print(z)

[0.3544238  0.30632722 0.91196085 0.44350311 0.44047615 0.5028352
 0.02821335 0.15392877 0.01425877 0.30273511]
[0.01425877 0.02821335 0.15392877 0.30273511 0.30632722 0.3544238
 0.44047615 0.44350311 0.5028352  0.91196085]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
Z = np.arange(10)
%timeit np.add.reduce(Z)
"""
%timeit: This is an IPython magic command used to time the execution of a single statement.
It runs the statement multiple times and provides the average time taken for execution.
np.add.reduce(Z): it performs a reduction operation on the array Z using addition.
Essentially, it sums all the elements of the array Z.
The reduce function applies the specified operation (in this case, addition) cumulatively to the elements of the array, reducing it to a single value.
"""

635 ns ± 2.37 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [62]:
%timeit np.sum(Z)

1.28 μs ± 2.56 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0, 2, (3, 3))
B = np.random.randint(0, 2, (3, 3))
A1 = np.random.randint(0, 2, 5)
B1 = np.random.randint(0, 2, 5)
print(A, B, A1, B1, sep="\n")
# assuming shapes are equal and checking elements
equal1 = np.allclose(A, B)
equal2 = np.allclose(A1, B1)
print(equal1, equal2)

# checking shapes and elements
equal1 = np.array_equal(A, B)
equal2 = np.array_equal(A1, B1)
print(equal1, equal2)

[[0 1 0]
 [0 1 1]
 [0 0 0]]
[[1 0 0]
 [1 0 1]
 [0 1 1]]
[1 1 0 1 1]
[0 1 1 1 0]
False False
False False


#### 43. Make an array immutable (read-only) (★★☆)

In [75]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
# print(Z,X,Y)
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y, X)
"""
The np.arctan2 function takes two input arrays, Y and X, which represent the y-coordinates and x-coordinates, respectively. It returns an array T 
containing the angle θ in radians between the positive x-axis and the point (X, Y).
This angle is measured counterclockwise from the positive x-axis, and it ranges from -π to π.
The function handles the signs of both inputs to determine the correct quadrant of the angle,
making it more robust than the standard arctan function, which only returns values between -π/2 and π/2.
"""
print(R)
print(T)

[0.58335982 1.0562113  1.11401891 0.48763215 1.10657314 1.0415464
 0.37435249 0.63445907 0.86913971 0.95119275]
[0.14290249 0.67979    0.77868913 0.21662813 0.93582741 0.81310823
 1.39190034 0.93172786 0.85393946 1.0916428 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
z = np.random.randint(1, 100, 10)
print(z)
z[z.argmax()] = 0
print(z)

[38 48 49 80 91 27 98 58 68  8]
[38 48 49 80 91 27  0 58 68  8]


In [ ]:
# z = np.random.randint(1,100,(5,2))
z = np.array([[95, 58], [46, 7], [16, 26],
              [43, 85],
              [60, 32]])
print(z)
# z.argmax(axis=0), z.argmax(axis=1)
print(z.argmax(axis=0))  # max along columns ie vertical axis
z[z.argmax(axis=0), (0, 1)] = 0  # replacing those indices with 0
print(z)
# z[(0,1,2,3),z.argmax(axis=1)]=0 #replacing max indices with 0 along horiz axis ie rows

[[95 58]
 [46  7]
 [16 26]
 [43 85]
 [60 32]]
[0 3]


array([[ 0, 58],
       [46,  7],
       [16, 26],
       [43,  0],
       [60, 32]])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
Z = np.zeros((5, 5), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(Z)

"""
The active selection of code creates a structured NumPy array with two fields, 'x' and 'y', both of type float. 
The array is initialized with zeros and has a shape of 5x5. 
The np.zeros is used to create this array, specifying the shape and the data type for each field.

Next, the code uses np.meshgrid to generate coordinate matrices from coordinate vectors.
np.linspace is used to create two 1-dimensional arrays with 5 evenly spaced values between 0 and 1.
These arrays are then passed to np.meshgrid, which returns two 2-dimensional arrays representing the grid coordinates.
The first array corresponds to the 'x' coordinates, and the second array corresponds to the 'y' coordinates.

The code then assigns these coordinate matrices to the 'x' and 'y' fields of the structured array Z

Finally, Z is printed, displaying the grid of coordinates where each element is a tuple containing the 'x' and 'y' values.

This approach is useful for creating a grid of points in a 2D space,
which can be used for various applications such as plotting, simulations, or numerical computations.
The use of structured arrays allows for easy access and manipulation of the coordinate data.
"""

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [98]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C), C.shape)

"""
C = 1.0 / np.subtract.outer(X, Y)
performs an element-wise operation between two arrays, and then computes the reciprocal of the result.

`np.subtract.outer(X, Y)`: computes the outer difference between two arrays, X and Y
The outer difference means that each element of X is subtracted from each element of Y, 
resulting in a new 2D array where the element at position (i, j) is X[i] - Y[j]
generating a matrix of differences between all pairs of elements from the two arrays.

`1.0 / ...`: After computing the outer difference, takes the reciprocal of each element
in the resulting 2D array C. 
The `1.0 /` operation ensures that the division is performed in floating-point arithmetic, 
which is important for maintaining precision.

The final result, C, is a 2D array where each element is the reciprocal of the difference 
between corresponding elements of X and Y. 
"""

3638.1636371179666 (8, 8)


'\nC = 1.0 / np.subtract.outer(X, Y)\nperforms an element-wise operation between two arrays, and then computes the reciprocal of the result.\n\n`np.subtract.outer(X, Y)`: computes the outer difference between two arrays, X and Y\nThe outer difference means that each element of X is subtracted from each element of Y, \nresulting in a new 2D array where the element at position (i, j) is X[i] - Y[j]\ngenerating a matrix of differences between all pairs of elements from the two arrays.\n\n`1.0 / ...`: After computing the outer difference, takes the reciprocal of each element\nin the resulting 2D array C. \nThe `1.0 /` operation ensures that the division is performed in floating-point arithmetic, \nwhich is important for maintaining precision.\n\nThe final result, C, is a 2D array where each element is the reciprocal of the difference \nbetween corresponding elements of X and Y. \n'

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40, 40))
print(Z)

"""
np.set_printoptions(threshold=float("inf")) is a line to configure how arrays are printed.
Specifically, it sets the threshold option to infinity. 
In NumPy, the set_printoptions function allows users to customize the way arrays are displayed when printed.
The threshold parameter controls the number of array elements that trigger summarization rather than printing the entire array. 
By default, if an array has more than 1000 elements, NumPy will summarize the array by showing only the first few and last few elements, 
with an ellipsis (`...`) in between to indicate omitted elements.

By setting threshold to float("inf"), the code effectively disables this summarization feature. 
The float("inf") expression represents positive infinity in Python, 
meaning that the threshold is set to an infinitely large number. 
As a result, NumPy will always print the full array without summarizing.
"""

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(Z-v)).argmin()
print(v, index, Z[index])

6.284923972135214 6 6


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
import numpy as np

Z = np.zeros(10, [('position', [('x', float, 1), ('y', float, 1)]),
                  ('color',    [('r', float, 1), ('g', float, 1), ('b', float, 1)])])
print(Z, Z.shape, sep="\n")
Z[0] = 99
print(Z)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]
(10,)
[(([99.], [99.]), ([99.], [99.], [99.]))
 (([ 0.], [ 0.]), ([ 0.], [ 0.], [ 0.]))
 (([ 0.], [ 0.]), ([ 0.], [ 0.], [ 0.]))
 (([ 0.], [ 0.]), ([ 0.], [ 0.], [ 0.]))
 (([ 0.], [ 0.]), ([ 0.], [ 0.], [ 0.]))
 (([ 0.], [ 0.]), ([ 0.], [ 0.], [ 0.]))
 (([ 0.], [ 0.]), ([ 0.], [ 0.], [ 0.]))
 (([ 0.], [ 0.]), ([ 0.], [ 0.], [ 0.]))
 (([ 0.], [ 0.]), ([ 0.], [ 0.], [ 0.]))
 (([ 0.], [ 0.]), ([ 0.], [ 0.], [ 0.]))]


In [ ]:
Z = np.zeros(10, [('position', [('x', float, 1), ('y', float, 1)])])
print(Z, Z.shape, sep="\n")
for i in range(4):
    Z[i]['position']['x'] = 100
for i in range(4, 8):
    Z[i]['position']['y'] = 666
for i in range(8, 10):
    Z[i]['position'] = 55, 77
print(Z)

[(([0.], [0.]),) (([0.], [0.]),) (([0.], [0.]),) (([0.], [0.]),)
 (([0.], [0.]),) (([0.], [0.]),) (([0.], [0.]),) (([0.], [0.]),)
 (([0.], [0.]),) (([0.], [0.]),)]
(10,)
[(([100.], [  0.]),) (([100.], [  0.]),) (([100.], [  0.]),)
 (([100.], [  0.]),) (([  0.], [666.]),) (([  0.], [666.]),)
 (([  0.], [666.]),) (([  0.], [666.]),) (([ 55.], [ 77.]),)
 (([ 55.], [ 77.]),)]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
import scipy.spatial
import scipy
Z = np.random.random((10, 2))
X, Y = np.atleast_2d(Z[:, 0], Z[:, 1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D.shape, D)

# Much faster with scipy

Z1 = np.random.random((10, 2))
D1 = scipy.spatial.distance.cdist(Z, Z)
print(D1 == D)

(10, 10) [[0.         0.06362472 0.33029203 0.25696646 0.45028377 0.54113861
  0.62815159 0.59657012 0.2516197  0.41851622]
 [0.06362472 0.         0.3924918  0.19436874 0.41455837 0.48355353
  0.58632627 0.57786461 0.25367686 0.48195675]
 [0.33029203 0.3924918  0.         0.57643477 0.65905187 0.82920561
  0.8435316  0.82544848 0.47493641 0.10429579]
 [0.25696646 0.19436874 0.57643477 0.         0.31754942 0.29985061
  0.45305837 0.60244869 0.37063622 0.67098342]
 [0.45028377 0.41455837 0.65905187 0.31754942 0.         0.2612076
  0.18568139 0.91996954 0.65716633 0.76330655]
 [0.54113861 0.48355353 0.82920561 0.29985061 0.2612076  0.
  0.24804791 0.830571   0.66457519 0.93087129]
 [0.62815159 0.58632627 0.8435316  0.45305837 0.18568139 0.24804791
  0.         1.04232314 0.81636475 0.94766858]
 [0.59657012 0.57786461 0.82544848 0.60244869 0.91996954 0.830571
  1.04232314 0.         0.35882016 0.86016944]
 [0.2516197  0.25367686 0.47493641 0.37063622 0.65716633 0.66457519
  0.81636475 0

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
Z = (np.random.rand(10)*100).astype(np.float32)
# print(Z,Z.astype(np.int32))
print(Z, Z.astype("int"), Z)
# complicated alternative
# Y = Z.view(np.int32)
# # print(Y)
# Y[:] = Z
# print(Y)

[43.61689  69.302444 45.924297 24.631538 42.038647 86.405624  8.279661
 27.626312 66.27222  64.29637 ] [43 69 45 24 42 86  8 27 66 64] [43.61689  69.302444 45.924297 24.631538 42.038647 86.405624  8.279661
 27.626312 66.27222  64.29637 ]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int32)
print(Z)
Y = np.where(Z == -1, 0, Z)
print(Y)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]
[[ 1  2  3  4  5]
 [ 6  0  0  7  8]
 [ 0  0  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
Z = np.arange(11, 77, 11).reshape(3, 2)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 11
(0, 1) 22
(1, 0) 33
(1, 1) 44
(2, 0) 55
(2, 1) 66
(0, 0) 11
(0, 1) 22
(1, 0) 33
(1, 1) 44
(2, 0) 55
(2, 1) 66


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2 / (2.0 * sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 3
p = 3
Z = np.zeros((n, n))
# np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
np.put(Z, np.random.choice(range(n*n), p, replace=False), (11, 22, 33))
# np.put(Z, np.random.choice(range(n*n), p, replace=False),range(1,4))
print(Z)

"""
np.random.choice(range(n*n), p, replace=False):generates a random selection of indices. The range(n*n) creates a sequence of numbers from 0 to n*n - 1.
then selects p unique indices from this range without replacement ie each index can only be selected once.

np.put(Z, ..., <value(or values in iterable)>): used to place values into the array Z at specified indices. 
The values (in order) is what will be placed into the array Z at each given/chosen indices.
"""

[[ 0. 22.  0.]
 [11.  0. 33.]
 [ 0.  0.  0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(5, 5)
print(X)

Y = X - X.mean(axis=1, keepdims=True)
print(Y)

"""
X.mean(axis=1, keepdims=True) calculates the mean of the elements along the specified axis (here, along row elementss).

Keep Dimensions: keepdims=True ensures that the dimensions of the result are the same as the original array X. Without this parameter, the result would be a 1-dimensional array of means. 
By keeping the dimensions, the result is a 2-dimensional array where each row contains the mean value of the corresponding row in X.

Broadcasting and Subtraction: The result of X.mean(axis=1, keepdims=True) is then subtracted from the original array X. This operation leverages NumPy's broadcasting feature, which allows arrays of different shapes to be combined in arithmetic operations. Here, the mean values (a 2D array with the same number of rows as X but only one column) are subtracted from each element in the corresponding row of X.

The overall effect of this line of code is to center the data in each row of X by subtracting the mean of that row from each element in the row. This is a common preprocessing step in data analysis and machine learning to normalize the data, ensuring that each feature has a mean of zero.
"""

[[0.70340405 0.98316052 0.35298814 0.37751682 0.31019637]
 [0.26328678 0.50034883 0.7224199  0.36698556 0.39540131]
 [0.31113915 0.93693847 0.01033892 0.50811005 0.80452187]
 [0.52539287 0.66922566 0.08303672 0.63773493 0.85406372]
 [0.44390453 0.54051896 0.2893065  0.43255233 0.06220147]]
[[ 0.15795087  0.43770734 -0.19246504 -0.16793636 -0.23525681]
 [-0.18640169  0.05066036  0.27273142 -0.08270292 -0.05428717]
 [-0.20307054  0.42272878 -0.50387078 -0.00609964  0.29031218]
 [-0.02849791  0.11533488 -0.47085406  0.08384415  0.30017294]
 [ 0.09020777  0.1868222  -0.06439026  0.07885558 -0.29149529]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
Z = np.random.randint(0, 100, (3, 3))
print(Z)
print(Z[Z[:, 1].argsort()])

"""
print(Z[Z[:,1].argsort()]) sorts the matrix Z based on the values in its second column.
Here, Z[:,1] extracts the second column of the matrix Z. 
The argsort() function is then called on this column, which returns the indices that would sort the column. 
By using these indices to index the original matrix Z, the entire matrix is rearranged such that the second column is sorted in ascending order.
"""

[[45 96 18]
 [ 4 21 41]
 [25 65  7]]
[[ 4 21 41]
 [25 65  7]
 [45 96 18]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
# null : 0
Z = np.random.randint(0, 3, (3, 3))
Z[:, 1] = 0
print(Z, (~Z.any(axis=0)).any())

"""
Z.any(axis=0) checks if any of the elements along the specified axis are True.
In this case, axis=0 means it checks each column of the array Z.
The result is a boolean array where each element represents whether any element in the corresponding column of Z is True (truthy).

The ~ operator is a bitwise NOT operator. When applied to a boolean array, it inverts the boolean values.
So, ~Z.any(axis=0) will produce a boolean array where True becomes False and False becomes True.
This effectively checks if all elements in each column are False (ie zero).

Finally, the outer .any() method is called on the resulting boolean array. 
This checks if any of the elements in the boolean array are True. 
In other words, it checks if there is at least one column in the original array Z that contains only False values ie 0.

Thus (~Z.any(axis=0)).any() evaluates to True if there is at least one column in Z of zeroes.
"""


# null : np.nan
Z = np.array([
    [0, 1, np.nan],
    [1, 2, np.nan],
    [4, 5, np.nan]
])
print(np.isnan(Z).all(axis=0))

"""
np.isnan(Z) checks each element in the array Z to determine if it is a NaN (Not a Number) value. 
The result of this function is a boolean array of the same shape as Z, 
where each element is True if the corresponding element in Z is NaN, and False otherwise.

the .all(axis=0) method is called on the resulting boolean array. 
The all() method checks whether all elements along a specified axis are True. 
In this case, axis=0 specifies that the check should be performed along the first axis (i.e., columns for a 2D array).
Therefore, np.isnan(Z).all(axis=0) returns a boolean array 
where each element is True if all elements in the corresponding column of Z are NaN, and False otherwise.
"""

[[2 0 1]
 [0 0 2]
 [2 0 1]] True
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
import numpy as np

Z = np.random.uniform(0, 1, 10).reshape(5, 2)
z = 0.5
ind = np.abs(Z - z).argmin()
m = Z.flat[ind]
print(Z, ind, m)

[[0.73179237 0.86908937]
 [0.98006396 0.42921921]
 [0.77908834 0.36145852]
 [0.86228922 0.81767507]
 [0.98426108 0.56787192]] 9 0.5678719206058883


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
it = np.nditer([A, B, None])
# for x,y,z in it: z[...] = x + y
for x, y, z in it:
    z = x + y

"""
`nditer` is used to create an iterator object that can iterate over multiple (broadcastable) arrays simultaneously.
In this case, A and B are the input arrays, and None is used to indicate that the iterator should also produce an output array.

np.nditer is quite powerful and flexible, allowing for efficient element-wise operations across arrays.
By passing [A, B, None] to np.nditer, you are setting up an iterator that will iterate over the elements of arrays A and B in a synchronized manner.
The None in the list signifies that the iterator should also generate an output array, which will be used to store the results of any operations performed during the iteration.

This is particularly useful when you need to perform operations that involve corresponding elements from multiple arrays and store the results in a new array.
The iterator ensures that the operations are performed efficiently and in a memory-conscious manner, leveraging NumPy's optimized internal routines.

Within the loop, the code z[...] = x + y performs an element-wise addition of x and y, and assigns the result to z. 
The [...] syntax is used to indicate that the entire array z should be updated with the result of x + y. This is a common idiom in NumPy.
But it is not needed here. It is more useful when we have 3+ dimnsional arrays for specifying indices during slicing in a concise manner.
For example: say we have a three_D array, then we can use three_D[...,:2] where ... represents all indices of first two dimns. 
Now, say we have a four_D array, then we can use four_D[1:,...,:2] where ... represents all indices of middle two dimns. and so on.
"""
print(it.operands[2].shape)
print(it.operands[2])
# print(A+B)
help(np.nditer)

(3, 3)
[[0 1 2]
 [1 2 3]
 [2 3 4]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
Help on class nditer in module numpy:

class nditer(builtins.object)
 |  nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K',
 |      casting='safe', op_axes=None, itershape=None, buffersize=0)
 |
 |  Efficient multi-dimensional iterator object to iterate over arrays.
 |  To get started using this object, see the
 |  :ref:`introductory guide to array iteration <arrays.nditer>`.
 |
 |  Parameters
 |  ----------
 |  op : ndarray or sequence of array_like
 |      The array(s) to iterate over.
 |
 |  flags : sequence of str, optional
 |        Flags to control the behavior of the iterator.
 |
 |        * ``buffered`` enables buffering when required.
 |        * ``c_index`` causes a C-order index to be tracked.
 |        * ``f_index`` causes a Fortran-order index to be tracked.
 |        * ``multi_index`` causes a multi-index, or a tuple of indices
 |          with one per iteration dimension, to be tracked.
 |      

#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class PJCArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, 'name', "no name")


Z = PJCArray(np.arange(10), "testing_name")
print(Z.name, Z, sep="\n")

"""
Here we define a custom subclass of numpy.ndarray called PJCArray.
This subclass allows for the addition of a name attribute to the array objects.
The class overrides two methods: __new__ and __array_finalize__.

The __new__ method is a special method in Python used for creating new instances of a class.
In this case, it takes three parameters: cls (the class itself), array (the array data), and name (an optional name for the array, defaulting to "no name").
Inside __new__, the np.asarray function is used to convert the input array to a numpy array, 
and then the view method is called to create a view of this array as an instance of PJCArray. 
The name attribute is then set on this new object, and the object is returned.

The __array_finalize__ method is called automatically whenever a new PJCArray object is created from an existing one (e.g., through slicing or other operations that return a new array).
This method ensures that the name attribute is preserved in the new array.
If the obj parameter is None, the method simply returns.
Otherwise, it uses the getattr function to retrieve the name attribute from the original object (obj), defaulting to "no name" if the attribute does not exist.
"""

testing_name
[0 1 2 3 4 5 6 7 8 9]


'\nHere we define a custom subclass of numpy.ndarray called PJCArray. This subclass allows for the addition of a name attribute to the array objects. The class overrides two methods: __new__ and __array_finalize__.\n\nThe __new__ method is a special method in Python used for creating new instances of a class. In this case, it takes three parameters: cls (the class itself), array (the array data), and name (an optional name for the array, defaulting to "no name"). Inside __new__, the np.asarray function is used to convert the input array to a numpy array, and then the view method is called to create a view of this array as an instance of PJCArray. The name attribute is then set on this new object, and the object is returned.\n\nThe __array_finalize__ method is called automatically whenever a new PJCArray object is created from an existing one (e.g., through slicing or other operations that return a new array). This method ensures that the name attribute is preserved in the new array. If

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [3]:
import numpy as np

Z = np.ones(10)
I = np.random.randint(0, len(Z), 20)
print(f"{Z=}")
print(f"{I=}")
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# np.add.at(Z, I, 1)
# print(Z)

Z = array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
I = array([7, 9, 4, 5, 3, 0, 5, 4, 3, 9, 2, 1, 0, 8, 8, 4, 9, 7, 8, 0])
[4. 2. 2. 3. 4. 3. 1. 3. 4. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [8]:
X = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]
F = np.bincount(I, X)
print(F)
a = np.arange(10)
# np.binary_repr(a)
a

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [15]:
x = np.array([0, 1, 2, 1, 2, 2, 2, 3, 22])
counts = np.bincount(x)
print(counts)

[1 2 4 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)